baseURL = "https://harrigan.xyz/"
author = "David Harrigan"
title = "harrigan.xyz"

languageCode = "en-us"
contentDir = "content"
publishDir = "public"
assetDir = "dist"
pluralizeListTitles = false
enableEmoji = true

googleAnalytics = "UA-117782664-1"

[taxonomies]
category = 'categories'
tag = 'tags'
series = 'series'

# [permalinks]
# posts = "/:sections/:slug/"
