baseURL = "https://harrigan.xyz/"
theme               = "PaperMod"
author              = "David Harrigan"
title               = "harrigan.xyz"

languageCode        = "en-us"
contentdir          = "content"
publishdir          = "public"
pygmentsUseClasses  = true
pluralizelisttitles = false
enableEmoji = true

disqusshortname     = "harrigan-xyz"
googleAnalytics     = "UA-117782664-1"

aliases = ['blog', 'posts']


[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[permalinks]
blog  = "blog/:slug/"
posts = "posts/:slug/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-frappe'
    tabWidth = 4

