[en]
languageName = "English"
weight = 1

  [en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10
