env = "development"
author = "David Harrigan"

comments = true
defaultTheme = "auto"
showShareButtons = true
showReadingTime = true
showPostNavLinks = true
showBreadCrumbs = true
showCodeCopyButtons = true
showToc = true

[editPost]
URL = "https://github.com/davidharrigan/davidharrigan.github.io/tree/main/content"
Text = "Suggest Changes"                                                           # edit text
appendFilePath = true                                                              # to append file path to Edit link
